# infra/docker-compose.yml
name: Webkit-OSINT

services:
  db:
    container_name: database
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: osint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: ["db-data:/var/lib/postgresql/data"]

  backend:
    container_name: backend
    build: ../backend
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/osint
    depends_on: [db]
    ports: ["8005:8005"]

  dashboard:
    container_name: dashboard
    build: ../dashboard
    depends_on: [backend]
    ports: ["3005:80"]
    
volumes:
  db-data:
